/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatprogramm.View;

/**
 *
 * @author nobody
 */
public class Fenster extends javax.swing.JFrame
{

    /**
     * @return the tfIPaddress
     */
    public javax.swing.JTextField getTfIPaddress() {
        return tfIPaddress;
    }

    /**
     * @return the cbServerClient
     */
    public javax.swing.JComboBox<String> getCbServerClient() {
        return cbServerClient;
    }
  /**
   * @return the btnConnect
   */
  public javax.swing.JButton getBtnConnect()
  {
    return btnConnect;
  }

  /**
   * @return the btnSend
   */
  public javax.swing.JButton getBtnSend()
  {
    return btnSend;
  }

  /**
   * @return the lblStatus
   */
  public javax.swing.JLabel getLblStatus()
  {
    return lblStatus;
  }

  /**
   * @return the taChat
   */
  public javax.swing.JTextArea getTaChat()
  {
    return taChat;
  }


  /**
   * @return the tfInput
   */
  public javax.swing.JTextField getTfInput()
  {
    return tfInput;
  }

  /**
   * Creates new form Fenster
   */
  public Fenster()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taChat = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfIPaddress = new javax.swing.JTextField();
        cbServerClient = new javax.swing.JComboBox<>();
        btnConnect = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        tfInput = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("chatprogramm");
        setPreferredSize(new java.awt.Dimension(500, 400));

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 250));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 350));

        taChat.setEditable(false);
        taChat.setColumns(20);
        taChat.setRows(5);
        taChat.setPreferredSize(new java.awt.Dimension(500, 350));
        jScrollPane1.setViewportView(taChat);

        jPanel2.add(jScrollPane1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setMaximumSize(new java.awt.Dimension(299, 48));

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("connect to server IP:");
        jPanel3.add(jLabel1);
        jPanel3.add(tfIPaddress);

        jPanel1.add(jPanel3);

        cbServerClient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Client", "Server" }));
        jPanel1.add(cbServerClient);

        btnConnect.setText("Connect");
        jPanel1.add(btnConnect);

        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStatus.setText("not connected");
        lblStatus.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(lblStatus);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        tfInput.setEnabled(false);
        tfInput.setPreferredSize(new java.awt.Dimension(500, 25));
        getContentPane().add(tfInput, java.awt.BorderLayout.CENTER);

        btnSend.setText("Send");
        btnSend.setEnabled(false);
        getContentPane().add(btnSend, java.awt.BorderLayout.LINE_END);

        setSize(new java.awt.Dimension(524, 376));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(Fenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(Fenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(Fenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(Fenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new Fenster().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnSend;
    private javax.swing.JComboBox<String> cbServerClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextArea taChat;
    private javax.swing.JTextField tfIPaddress;
    private javax.swing.JTextField tfInput;
    // End of variables declaration//GEN-END:variables
}
